apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-first-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      project: myProject
      var: 0.1
  template:
    metadata:
      name: my-first-pod
      labels:
        project: myProject
        var: 0.1
    spec:
      containers:
      - name: my-container
        image: nginx
        ports:
        - containerPort: 80